spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/feedback
  application:
   name: feedback-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/realms/store
server:
  port: 8085